home/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import register_view, AddUser, UserDetailView, UserList, UserChangeView, UserPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('accounts/login', LoginView.as_view(), name='login'),
    path('accounts/logout', LogoutView.as_view(), name='logout'),
    path('add_user_in_project/<int:pk>', AddUser.as_view(), name='add_user'),
    path('delete_user_in_project/<int:pk>', AddUser.as_view(), name='delete_user'),
    path('register/', register_view, name='register'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('users/', UserList.as_view(), name='user_list'),
    path('change/', UserChangeView.as_view(), name='change'),
    path('password_change/', UserPasswordChangeView.as_view(), name='password_change')
]

home/home/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


HOMEPAGE_URL = 'projects/'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('', RedirectView.as_view(url=HOMEPAGE_URL, permanent=False))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/webapp/urls.py
from django.urls import path
from webapp.views.project import ProjectList, ProjectCreate, ProjectView, ProjectDelete, ProjectEdit
from webapp.views.task import TaskCreate, TaskEdit, TaskView, TaskDelete

app_name = 'webapp'

urlpatterns = [
    path('', ProjectList.as_view(), name='home' ),
    path('create/project/', ProjectCreate.as_view(), name='create'),
    path('view/<int:pk>/project/', ProjectView.as_view(), name='view'),
    path('delete/<int:pk>/project/', ProjectDelete.as_view(), name='delete'),
    path('<int:pk>/create/task/', TaskCreate.as_view(), name='create_task'),
    path('view/task/<int:pk>/', TaskView.as_view(), name='view_task'),
    path('delete/task/<int:pk>/', TaskDelete.as_view(), name='delete_task'),
    path('edit/task/<int:pk>/', TaskEdit.as_view(), name='edit_task'),
    path('edit/<int:pk>/project', ProjectEdit.as_view(), name='edit')

]

home/webapp/models.py
from django.db import models
from webapp.validator import MinLengthValidator
from django.contrib.auth import get_user_model

# Create your models here.
class TimeBase(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Type(models.Model):
    name = models.CharField(max_length=200, null=False, blank=False)

    class Meta:
        db_table = 'Type'
        verbose_name = 'Тип'
        verbose_name_plural = 'Типы'

    def __str__(self):
        return f"{self.name}"

class Status(models.Model):
    name = models.CharField(max_length=200, null=False, blank=False)

    class Meta:
        db_table = 'Status'
        verbose_name = 'Статус'
        verbose_name_plural = 'Статусы'

    def __str__(self):
        return f"{self.name}"


class Task(TimeBase):
    summary = models.CharField(max_length=300, null=False, blank=False, validators=(MinLengthValidator(5),))
    description = models.TextField(max_length=3000, null=True, blank=True, validators=(MinLengthValidator(5),))
    status = models.ForeignKey('webapp.Status', on_delete=models.CASCADE, related_name='status', verbose_name='Статус')
    type = models.ManyToManyField('webapp.Type', related_name='tasks', through='webapp.TaskType', through_fields=('task', 'type'))
    project = models.ForeignKey('webapp.Project', on_delete=models.CASCADE, related_name='project', verbose_name='Проект')

    class Meta:
        db_table = 'Task'
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'

    def __str__(self):
        return f'{self.id}. {self.summary}: {self.description}'



class TaskType(models.Model):
    task = models.ForeignKey('webapp.Task', related_name='task_type', on_delete=models.CASCADE, verbose_name='Задача')
    type = models.ForeignKey('webapp.Type', related_name='type_task', on_delete=models.CASCADE, verbose_name='Тег')

    def __str__(self):
        return "{} | {}".format(self.task, self.type)

class Project(models.Model):
    timestart = models.DateField(null=False, blank=False)
    timefinish = models.DateField(null=True, blank=True)
    name = models.CharField(max_length=300, null=False, blank=False, validators=(MinLengthValidator(4),))
    description = models.TextField(max_length=3000, null=False, blank=False, validators=(MinLengthValidator(10),))
    user = models.ManyToManyField(get_user_model(), default=1, related_name='projects', verbose_name='Пользователь')

    class Meta:
        db_table = 'Project'
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'
        permissions = [
            ('user_add_or_del', 'Удаление или добавление')
        ]

    def __str__(self):
        return f'{self.name} : {self.description}'

home/webapp/forms.py
from django import forms
from django.forms import widgets
from webapp.models import Status, Type, Task, Project
#
# class TaskForm(forms.Form):
#     summary = forms.CharField(max_length=200, required=True, label='Summary')
#     description = forms.CharField(max_length=3000, label='Description', required=False, widget=widgets.Textarea)
#     status = forms.ModelChoiceField(queryset=Status.objects.all())
#     type = forms.ModelMultipleChoiceField(queryset=Type.objects.all())

class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ('summary', 'description', 'status', 'type')


class SearchForm(forms.Form):
    search_value = forms.CharField(max_length=100, required=False, label='Найти')



class ProjectForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = ('name', 'description', 'timestart', 'timefinish')

home/webapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View, TemplateView, RedirectView, FormView, ListView
from django.http import HttpResponseRedirect, HttpResponseNotFound, Http404
from webapp.models import Task
from webapp.forms import TaskForm, SearchForm
from webapp.base_views import FormView as CustomFormView
from django.urls import reverse
from django.db.models import Q
from django.utils.http import urlencode
# Create your views here.

class List_tasks(ListView):
    template_name = 'list.html'
    model = Task
    context_object_name = 'tasks'
    ordering = ('summary', '-created_at')
    paginate_by = 10
    paginate_orphans = 2

    def get(self, request, **kwargs):
        self.form = SearchForm(request.GET)
        self.search_data = self.get_search_data()
        return super(List_tasks, self).get(request, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()

        if self.search_data:
            queryset = queryset.filter(
                Q(summary__icontains=self.search_data) |
                Q(description__icontains=self.search_data)
            )
        return queryset

    def get_search_data(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search_value']
        return None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_form'] = self.form
        if self.search_data:
            context['query'] = urlencode({'search_value': self.search_data})
        return context


class Create_task(CustomFormView):
    template_name = 'create.html'
    form_class = TaskForm
    redirect_url = 'home'

    def form_valid(self, form):
        type = form.cleaned_data.pop('type')
        task = Task()
        for key, value in form.cleaned_data.items():
            setattr(task, key, value)

        task.save()
        task.type.set(type)

        return super().form_valid(form)


class Edit_task(FormView):
    template_name = 'edit.html'
    form_class = TaskForm

    def dispatch(self, request, *args, **kwargs):
        self.task = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['task'] = self.task
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['instance'] = self.task
        return kwargs

    def form_valid(self, form):
        self.task = form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('view', kwargs={'pk': self.task.pk})

    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Task, pk=pk)



class View_task(View):
    def get(self, request, *args, **kwargs):
        try:
            task = get_object_or_404(Task, id=kwargs.get('pk'))
        except:
            raise Http404
        return render(request, 'view.html', {'task':task})


class Delete_task(View):
    def get(self, request, *args, **kwargs):
        task = get_object_or_404(Task, id=kwargs.get('pk'))
        return render(request, 'delete.html', {'task': task})
    def post(self, request, *args, **kwargs):
        task = get_object_or_404(Task, id=kwargs.get('pk'))
        task.delete()
        return redirect('home')

home/webapp/views/project.py
from django.views.generic import View, TemplateView, RedirectView, FormView, ListView, CreateView, DetailView, UpdateView, DeleteView
from webapp.models import Project
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from webapp.forms import ProjectForm, SearchForm, TaskForm
from webapp.models import Project, Task
from django.db.models import Q
from django.utils.http import urlencode
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.contrib.auth.models import User

class ProjectCreate(PermissionRequiredMixin, CreateView):
    template_name = 'project/create.html'
    form_class = ProjectForm
    model = Project
    permission_required = 'webapp.add_project'

    def form_valid(self, form):
        user = self.request.user
        project = form.save()
        project.user.add(user)
        return redirect('webapp:view', pk=project.pk)


    # def get_success_url(self):
    #     return reverse('webapp:view', kwargs={'pk' : self.object.pk})



class ProjectList(ListView):
    template_name = 'project/list.html'
    model = Project
    context_object_name = 'projects'
    ordering = ('name', '-timestart')
    paginate_by = 10
    paginate_orphans = 2

    def get(self, request, **kwargs):
        self.form = SearchForm(request.GET)
        self.search_data = self.get_search_data()
        return super(ProjectList, self).get(request, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()

        if self.search_data:
            queryset = queryset.filter(
                Q(name__icontains=self.search_data) |
                Q(description__icontains=self.search_data)
            )
        return queryset

    def get_search_data(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search_value']
        return None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_form'] = self.form

        if self.search_data:
            context['query'] = urlencode({'search_value': self.search_data})

        return context


class ProjectEdit(PermissionRequiredMixin, UpdateView):
    model = Project
    template_name = 'project/edit.html'
    form_class = ProjectForm
    context_object_name = 'project'
    permission_required = 'webapp.change_project'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:view', kwargs={'pk': self.object.pk})



class ProjectView(DetailView):
    model = Project
    template_name = 'project/view.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)


class ProjectDelete(PermissionRequiredMixin, DeleteView):
    template_name = 'project/delete.html'
    model = Project
    context_object_name = 'project'
    success_url = reverse_lazy('webapp:home')
    permission_required = 'webapp.delete_project'

    def has_permission(self):
        return super().has_permission() and self.request.user in self.get_object().user.all()

home/webapp/views/task.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View, TemplateView, RedirectView, FormView, ListView, CreateView, DetailView, UpdateView, DeleteView
from django.http import HttpResponseRedirect, HttpResponseNotFound, Http404
from webapp.models import Task, Project
from webapp.forms import TaskForm, SearchForm
from webapp.base_views import FormView as CustomFormView
from django.urls import reverse, reverse_lazy
from django.db.models import Q
from django.utils.http import urlencode
from django.contrib.auth.mixins import PermissionRequiredMixin
# Create your views here.

# class TaskList(ListView):
#     template_name = 'task/list.html'
#     model = Task
#     context_object_name = 'tasks'
#     ordering = ('summary', '-created_at')
#     paginate_by = 10
#     paginate_orphans = 2
#
#     def get(self, request, **kwargs):
#         self.form = SearchForm(request.GET)
#         self.search_data = self.get_search_data()
#         return super(List_tasks, self).get(request, **kwargs)
#
#     def get_queryset(self):
#         queryset = super().get_queryset()
#
#         if self.search_data:
#             queryset = queryset.filter(
#                 Q(summary__icontains=self.search_data) |
#                 Q(description__icontains=self.search_data)
#             )
#         return queryset
#
#     def get_search_data(self):
#         if self.form.is_valid():
#             return self.form.cleaned_data['search_value']
#         return None
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['search_form'] = self.form
#         if self.search_data:
#             context['query'] = urlencode({'search_value': self.search_data})
#         return context


class TaskCreate(PermissionRequiredMixin, CreateView):
    model = Task
    template_name = 'task/create.html'
    form_class = TaskForm
    permission_required = 'webapp.add_task'

    def has_permission(self):
        project = get_object_or_404(Project, pk=self.kwargs.get('pk'))
        return super().has_permission() and self.request.user in project.user.all()

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        project = get_object_or_404(Project, pk=self.kwargs.get('pk'))
        task = form.save(commit=False)
        task.project = project
        task.save()
        form.save_m2m()
        return redirect('webapp:view_task', pk=task.pk)




class TaskEdit(PermissionRequiredMixin, UpdateView):
    model = Task
    template_name = 'task/edit.html'
    form_class = TaskForm
    context_object_name = 'task'
    permission_required = 'webapp.change_task'

    def has_permission(self):
        # task = get_object_or_404(Task, pk=self.kwargs.get('pk'))
        task = self.get_object()
        return super().has_permission() and self.request.user in task.project.user.all()

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:view_task', kwargs={'pk': self.object.pk})



class TaskView(PermissionRequiredMixin, DetailView):
    model = Task
    template_name = 'task/view.html'
    permission_required = 'webapp.view_task'

    def has_permission(self):
        task = self.get_object()
        return super().has_permission() and self.request.user in task.project.user.all()


class TaskDelete(PermissionRequiredMixin, DeleteView):
    template_name = 'task/delete.html'
    model = Task
    context_object_name = 'task'
    permission_required = 'webapp.delete_task'

    def has_permission(self):
        task = self.get_object()
        return super().has_permission() and self.request.user in task.project.user.all()

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:view', kwargs={'pk': self.object.project.pk})

home/webapp/templates/project/create.html
{% extends 'base.html' %}

{% block content %}
    <h1>Create Project</h1>
<form action="{% url 'webapp:create' %}" method="post">

    {% include 'partial/form.html'  with button_text='Create' %}

</form>
{% endblock %}

home/webapp/templates/project/delete.html
{% extends 'base.html' %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
</head>
<body>
{% block content %}


    <h1>Are you sure want to delete Project "{{ project }}"?</h1>
    <form method="POST" action="{% url "webapp:delete" project.pk %}" class="text-center">
        {% csrf_token %}
        <p><input type="submit" value="Yeas!"></p>
        <a class="btn btn-primary" href="{% url 'webapp:home' %}" role="button">No!</a>
    </form>







<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
{% endblock %}
</body>
</html>

home/webapp/templates/project/edit.html
{% extends 'base.html' %}
{% block content %}
    <h1>Edit Project</h1>
<form action="{% url 'webapp:edit' project.pk %}" method="post">

    {% include 'partial/form.html'  with button_text='Edit' %}

</form>
{% endblock %}

home/webapp/templates/project/list.html
{% extends 'base.html' %}
{% block title %}Hello{% endblock %}
{% block content %}
{% if not projects %}
    <h2 class="text-center">Нет Проектов</h2>
{% else %}
    {% include "partial/search_form.html" %}
{% endif %}
    <h1>Projects</h1>
    {% include 'partial/project_list.html' %}
{% endblock %}

home/webapp/templates/project/view.html
{% extends 'base.html' %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
</head>
<body>
{% block content %}
<div class="container">
<h3>ProjectName : {{ project.name }}</h3>
<br>
<br>
<p>Description: {{ project.description }}</p>
    <h4>Users:</h4>
    {% for i in project.user.all %}
    <p><a href="{% url 'accounts:detail' i.id %}">{{ i }}</a></p>
    {% endfor %}

    <h2>Tasks:</h2>
{% for task in project.project.all %}
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{ task.summary }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ task.description }}</h6>
                <p class="card-text">Type: {% for type in task.type.all %}{{ type.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
                {% if perms.webapp.change_task and request.user in project.user.all %}
                <a href="{% url 'webapp:edit_task' task.pk %}" class="card-link">Edit</a>
                {% endif %}
                {% if perms.webapp.delete_task and request.user in project.user.all %}
                <a href="{% url 'webapp:delete_task' task.pk %}" class="card-link">Delete</a>
                {% endif %}
                {% if perms.webapp.view_task and request.user in project.user.all %}
                <a href="{% url 'webapp:view_task' task.pk %}" class="card-link">More..</a>
                {% endif %}
            </div>
        </div>
        <br>
{% if not task %}
    <h2>НЕТ ЗАДАЧ!</h2>
{% endif %}
{% endfor %}
</div>
{% endblock %}
    {% block menu %}
    {% if perms.webapp.delete_project and request.user in project.user.all %}
    <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="{% url 'webapp:delete' project.pk %}">Delete</a>
    </li>
    {% endif %}
    {% if perms.webapp.add_project and request.user in project.user.all %}
    <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="{% url 'webapp:create_task' project.pk %}">CreateNewTask</a>
    </li>
    {% endif %}
    {% if perms.webapp.change_project and request.user in project.user.all %}
    <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="{% url 'webapp:edit' project.pk %}">EditProject</a>
    </li>
    {% endif %}
    {% if perms.webapp.change_project and request.user in project.user.all %}
    <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="{% url 'accounts:add_user' project.pk %}">Add User</a>
    </li>
    {% endif %}
    {% if perms.webapp.change_project and request.user in project.user.all %}
    <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="{% url 'accounts:delete_user' project.pk %}">Delete User</a>
    </li>
    {% endif %}
    {% endblock %}









<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
</body>
</html>