home/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import register_view, AddUser, UserDetailView, UserList, UserChangeView, UserPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('accounts/login', LoginView.as_view(), name='login'),
    path('accounts/logout', LogoutView.as_view(), name='logout'),
    path('add_user_in_project/<int:pk>', AddUser.as_view(), name='add_user'),
    path('delete_user_in_project/<int:pk>', AddUser.as_view(), name='delete_user'),
    path('register/', register_view, name='register'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('users/', UserList.as_view(), name='user_list'),
    path('change/', UserChangeView.as_view(), name='change'),
    path('password_change/', UserPasswordChangeView.as_view(), name='password_change')
]

home/home/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


HOMEPAGE_URL = 'projects/'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('', RedirectView.as_view(url=HOMEPAGE_URL, permanent=False))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), related_name='profile', on_delete=models.CASCADE, verbose_name='Пользователь', blank=True, null=True)
    link = models.URLField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=1000, blank=True, null=False)
    avatar = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name='Аватар')

    def __str__(self):
        return self.user.get_full_name() + "'s Profile"

    class Meta:
        db_table = 'Profile'
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'
        permissions = [
            ('view_user', 'Обзор Юзеров')
        ]

home/accounts/forms.py
from django.contrib.auth.models import User
from webapp.models import Project
from django import forms
from accounts.models import Profile
from django.contrib.auth import get_user_model



class MyUserCreationForm(forms.ModelForm):
    password = forms.CharField(label="Пароль", strip=False, required=True, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Подтвердите пароль", required=True, widget=forms.PasswordInput, strip=False)
    email = forms.CharField(label='Email', required=True)

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_confirm = cleaned_data.get("password_confirm")
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        if not first_name and not last_name:
            raise forms.ValidationError('Заполните хотябы одно из полей FirstName, LastName')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['username', 'password', 'password_confirm', 'first_name', 'last_name', 'email']

class MyUserUpdate(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['user',]


class UserChangeForm(forms.ModelForm):

    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email'}


class ProfileChangeForm(forms.ModelForm):

    class Meta:
        model = Profile
        exclude = ['user']


class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(label="Новый пароль", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Подтвердите пароль", widget=forms.PasswordInput, strip=False)
    old_password = forms.CharField(label="Старый пароль", strip=False, widget=forms.PasswordInput)


    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        return password_confirm


    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Старый пароль неправильный!')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ['password', 'password_confirm', 'old_password']

home/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from accounts.forms import MyUserCreationForm

# Create your views here.

# def login_view(request):
#     context = {}
#     if request.method == 'POST':
#         username = request.POST.get('username')
#         password = request.POST.get('password')
#         user = authenticate(request, username=username, password=password)
#         if user is not None:
#             login(request,user)
#             return redirect('home')
#         else:
#             context['has_error'] = True
#     return render(request, 'login.html', context=context)
#
#
# def logout_view(request):
#     logout(request)
#     return redirect('home')

def register_view(request, *args, **kwargs):
    if request.method == 'POST':
        form = MyUserCreationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('webapp:home')
    else:
        form = MyUserCreationForm()
    return render(request, 'user_create.html', context={'form': form})

home/accounts/views/profile.py
from django.views.generic import DetailView, ListView, UpdateView
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from accounts.models import Profile
from accounts.forms import UserChangeForm, ProfileChangeForm, PasswordChangeForm
from django.http import HttpResponseRedirect


class UserDetailView(DetailView):
    model = get_user_model()
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'
    paginate_related_by = 5
    paginate_related_orphans = 0

    def get_context_data(self, **kwargs):
        projects = self.object.projects.order_by('-timestart')
        paginator = Paginator(projects, self.paginate_related_by, orphans=self.paginate_related_orphans)
        page_number = self.request.GET.get('page', 1)
        page = paginator.get_page(page_number)
        kwargs['page_obj'] = page
        kwargs['projects'] = page.object_list
        kwargs['is_paginated'] = page.has_other_pages()
        kwargs['profile'] = get_object_or_404(Profile, pk=self.kwargs.get('pk'))
        return super().get_context_data(**kwargs)


class UserList(PermissionRequiredMixin, ListView):
    template_name = 'user_list.html'
    model = get_user_model()
    context_object_name = 'users'
    ordering = ('username',)
    permission_required = 'accounts.view_user'

    def has_permission(self):
        return super().has_permission()

class UserChangeView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'user_change.html'
    context_object_name = 'user_obj'

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        if 'profile_form' not in kwargs:
            kwargs['profile_form'] = self.get_profile_form()
            return super().get_context_data(**kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        profile_form = self.get_profile_form()
        if form.is_valid() and profile_form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        response = super().form_valid(form)
        profile_form.save()
        return response

    def form_invalid(self, form, profile_form):
        context = self.get_context_data(form=form, profile_form=profile_form)
        return self.render_to_response(context)

    def get_profile_form(self):
        form_kwargs = {'instance': self.object.profile}
        if self.request.method == 'POST':
            form_kwargs['data'] = self.request.POST
            form_kwargs['files'] = self.request.FILES
        return ProfileChangeForm(**form_kwargs)

    def get_success_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.object.pk})


class UserPasswordChangeView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    template_name = 'user_password_change.html'
    form_class = PasswordChangeForm
    context_object_name = 'user_obj'

    def form_valid(self, form):
        user = form.save()
        update_session_auth_hash(self.request, user)
        return HttpResponseRedirect(self.get_success_url())

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.object.pk})

home/accounts/views/registration.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from accounts.forms import MyUserCreationForm
from accounts.models import Profile

# Create your views here.

# def login_view(request):
#     context = {}
#     if request.method == 'POST':
#         username = request.POST.get('username')
#         password = request.POST.get('password')
#         user = authenticate(request, username=username, password=password)
#         if user is not None:
#             login(request,user)
#             return redirect('home')
#         else:
#             context['has_error'] = True
#     return render(request, 'login.html', context=context)
#
#
# def logout_view(request):
#     logout(request)
#     return redirect('home')

def register_view(request, *args, **kwargs):
    if request.method == 'POST':
        form = MyUserCreationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            user.save()
            Profile.objects.create(user=user)
            return redirect('webapp:home')
    else:
        form = MyUserCreationForm()
    return render(request, 'user_create.html', context={'form': form})

home/accounts/views/user_add.py
from django.views.generic import View, TemplateView, RedirectView, FormView, ListView, CreateView, DetailView, UpdateView, DeleteView
from webapp.models import Project
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from accounts.forms import MyUserUpdate
from webapp.models import Project, Task
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import User


class AddUser(PermissionRequiredMixin, UpdateView):
    model = Project
    template_name = 'user_add.html'
    form_class = MyUserUpdate
    context_object_name = 'project'
    permission_required = 'webapp.user_add_or_del'

    def has_permission(self):
        return super().has_permission() and self.request.user in self.get_object().user.all()


    def get_success_url(self):
        return reverse('webapp:view', kwargs={'pk': self.object.pk})

home/accounts/templates/user_add.html
{% extends 'base.html' %}
{% block content %}
    <h1>Add User</h1>
<form action="{% url 'accounts:add_user' project.pk %}" method="post">

    {% include 'partial/form.html'  with button_text='Add' %}

</form>
{% endblock %}

home/accounts/templates/user_change.html
{% extends 'base.html' %}
{% block title %}Редактировать пользователя{% endblock %}

{% block menu_links %}
    <li><a href="{% url "accounts:detail" user_obj.pk %}">Назад</a></li>
    <li><a href="#">Смена пароля</a></li>
{% endblock %}

{% block content %}
    <h1>Поменять личные данные</h1>
    <form action="{% url 'accounts:change' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'partial/form.html' with form=form fields_only=True %}
        {% include 'partial/form.html' with form=profile_form fields_only=True %}
        <br>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

home/accounts/templates/user_create.html
{% extends 'base.html' %}
{% block title %}Регистрация{% endblock %}

{% block content %}
    <h1>Регистрация</h1>
<form action="{% url 'accounts:register' %}" method="post">
     {% include 'partial/form.html' with button_text="Зарегистрироваться" %}
</form>

{% endblock %}

home/accounts/templates/user_detail.html
{% extends 'base.html' %}
{% block title %}Пользователь{% endblock %}
{% block menu %}
{% if request.user == user_obj %}
    <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="{% url 'accounts:change' %}">Редактировать</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="{% url 'accounts:password_change' %}">Смена пароля</a>
    </li>
{% endif %}
{% endblock %}
{% block content %}
    <h1>Личная страница пользователя {{ user_obj.get_full_name|default:user_obj.username }}</h1>
    {% if user_obj.profile.avatar %}
        <img class="avatar" src="{{ user_obj.profile.avatar.url }}" width="250" height="250" alt="user picture">
    {% endif %}
    {% if user_obj.profile.link %}
        <p>URL: {{ user_obj.profile.link }}</p>
    {% endif %}
    {% if user_obj.profile.description %}
    <p>Описание: {{ user_obj.profile.description }}</p>
    {% endif %}
    <p>Имя пользователя: {{ user_obj.username }}</p>
    <p>Имя: {{ user_obj.first_name }}</p>
    <p>Фамилия: {{ user_obj.last_name }}</p>
    <p>Дата рождения: {{ user_obj.profile.birth_date|date:'d.m.Y' }}</p>
 <p>Почта: {{ user_obj.email }}</p>

    <h2 class="text-center clear">Проекты Пользователя:</h2>
    {% include 'partial/project_list.html' %}
{% endblock %}

home/accounts/templates/user_list.html
{% extends 'base.html' %}
{% block menu_links %}
{% endblock %}
{% block content %}
<h1>Profiles:</h1>
{% for i in users %}
        <p>
            <a href="{% url 'accounts:detail' i.id %}">{{ i.username }}</a>
        </p>
{% endfor %}
{% endblock %}

home/accounts/templates/user_password_change.html
{% extends 'base.html' %}
{% block title %}Смена пароля{% endblock %}

{% block menu_links %}
    <li><a href="{% url "accounts:detail" user_obj.pk %}">Назад</a></li>
    <li><a href="{% url "accounts:change" user_obj.pk %}">Редактирование личных данных</a></li>
{% endblock %}


{% block content %}
    <h1>Смена пароля</h1>
    {% url "accounts:password_change" as action_url %}
    {% include 'partial/form.html' with action_url=action_url form_method="post" %}
{% endblock %}